[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "transcriber"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyinstaller>=6.17.0",
    "whisperx>=3.7.4",
    "psutil>=5.9.0",
    "mutagen>=1.47.0",
    "pydantic>=2.12.5",
    "huey>=2.5.0",
    "pytorch-lightning>=2.1.0",
    "torchmetrics>=1.2.0",
]

[tool.setuptools.packages.find]
include = ["transcriber*", "model_manager*", "resource_tracker*"]
